**Welcome to Numpy Tutorial**

In [ ]:
import numpy as np

**Creating numpy array using python object**

In [12]:
myarr = np.array([3,6,4,3,2,11], np.int32)

In [13]:
print(myarr)
print(myarr.dtype)

[ 3  6  4  3  2 11]
int32


In [14]:
arr = np.array([[11,21,51]])

print(arr[0,1])

print(arr.shape)

21
(1, 3)


In [15]:
arr[0,1] = 69
arr

array([[11, 69, 51]])

In [16]:
list_array = np.array([[1,2,3], [23,2,1], [1,0,1]], np.int32)

In [18]:
print(list_array)
print(list_array.shape)
print(list_array.dtype)
list_array.size

[[ 1  2  3]
 [23  2  1]
 [ 1  0  1]]
(3, 3)
int32


9

In [20]:
print(np.array({2,1,0,1}).dtype)

print("when we crete numpy array using sets in python then the dtype will be 'object'" \
"which is not so effecient for mathematical calculations")

object
when we crete numpy array using sets in python then the dtype will be 'object'which is not so effecient for mathematical calculations


In [24]:
zeroes = np.zeros((6,2))

print(zeroes)

print(zeroes.shape)
print(zeroes.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(6, 2)
float64


In [27]:
rng = np.arange(15)
print(rng)
print(type(rng))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [28]:
lspace = np.linspace(1,50,10)
print(lspace)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [30]:
emp = np.empty((4,6))
print(emp)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.95822389e-306
  1.29060531e-306 8.45599366e-307]
 [7.56593017e-307 1.11258854e-306 1.11261502e-306 1.42410839e-306
  7.56597770e-307 6.23059726e-307]
 [9.34608432e-307 1.11261027e-306 1.29061414e-306 6.89807188e-307
  1.60220393e-306 7.56599807e-307]
 [8.06638080e-308 8.34424342e-308 1.11260483e-306 1.11256749e-306
  6.23058368e-307 8.91253127e-313]]


In [31]:
emp_like = np.empty_like(lspace)
print(emp_like)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [33]:
ide = np.identity(45)
print(ide)
print(ide.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(45, 45)


In [34]:
arr1 = np.arange(99)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [37]:
arr = arr1.reshape(3,33)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [40]:
arr1.ravel
print(arr1)
print(arr1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
(99,)


**Numpy Axis**

-1D ARRAY -> 1 AXIS : [AXIS 0] -------> axis 0


-2D ARRAY -> 2 AXIS : [AXIS 0] [AXIS 1]   axis 0 |---------> axis 1
                                          
                                         

In [41]:
x = [[1,2,3], [4,5,6], [7,1,0]]
ar = np.array(x)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [42]:
ar.sum(axis=0)

array([12,  8,  9])

In [43]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [46]:
print(ar.T)

[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [56]:
for item in ar.flat:
    print(item)

print(ar.flat)

1
2
3
4
5
6
7
1
0


In [49]:
print(ar.ndim)

2


In [50]:
print(ar.size)

9


In [51]:
print(ar.nbytes)

72


In [52]:
print(ar.dtype)

int64


In [58]:
one = np.array([1,2,2,3,2,1])

print(one.argmax())
print(one.argmin())
print(one.argsort())

3
0
[0 5 2 1 4 3]


In [60]:
print(ar.argmin())

8


In [61]:
print(ar.argmax())

6


In [62]:
print(ar.argmax(axis=0))

[2 1 1]


In [63]:
print(ar.argmax(axis=1))

[2 2 0]


In [64]:
print(ar.argsort(axis=0))

[[0 2 2]
 [1 0 0]
 [2 1 1]]


In [65]:
print(ar.reshape(9,))

[1 2 3 4 5 6 7 1 0]


In [67]:
ar2 = np.array([[12,3,1], [1,1,1], [1,0,0]])

print(ar+ar2)

[[13  5  4]
 [ 5  6  7]
 [ 8  1  0]]


In [68]:
print(ar*ar2)

[[12  6  3]
 [ 4  5  6]
 [ 7  0  0]]


In [69]:
print(np.sqrt(ar))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 1.         0.        ]]


In [71]:
print(ar.sum())

29


In [72]:
print(np.where(ar>5))

(array([1, 2]), array([2, 0]))


In [73]:
print(np.count_nonzero(ar))

8


In [74]:
print(np.nonzero(ar))

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))


In [75]:
import sys 


In [76]:
py_ar = [0,4,55,2]


In [77]:
np_ar = np.array([0,4,55,2])

In [80]:
print(sys.getsizeof(1)*len(py_ar))
print(np_ar.itemsize*np_ar.size)

112
32
